ADMINISTRATOR = "Administrator"
MODERATOR = "Moderator"
PRVA_GODINA = "Prva godina"
DRUGA_GODINA = "Druga godina"
TRECA_GODINA = "Treća godina"
CETVRTA_GODINA = "Četvrta godina"
APSOLVENT = "Apsolvent"
IMATRIKULANT = "Imatrikulant"
ALUMNI = "Alumni"
MUTED = "Muted"
REGISTROVAN = "Registrovan"
NEREGISTROVAN = "Neregistrovan(a)"

EVERYONE = "@everyone"