"""Add default to output youtube

Revision ID: 02efc5160919
Revises: 06a0f08ce4a7
Create Date: 2020-01-10 09:14:27.305695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02efc5160919'
down_revision = '06a0f08ce4a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Youtube', 'Output',
               existing_type=sa.BOOLEAN(),
               nullable=False, server_default=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Youtube', 'Output',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
