"""Add output columnt youtube

Revision ID: 06a0f08ce4a7
Revises: 24cc81d266c7
Create Date: 2020-01-10 09:07:14.897835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a0f08ce4a7'
down_revision = '24cc81d266c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Youtube', sa.Column('Output', sa.Boolean()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Youtube', 'Output')
    # ### end Alembic commands ###
