"""Add Id as prim key to Youtube

Revision ID: 11503172cc9a
Revises: 
Create Date: 2020-01-10 08:56:46.380600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11503172cc9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Youtube', sa.Column('Id', sa.Integer()))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Youtube', 'Id')
    # ### end Alembic commands ###
