"""Add source column

Revision ID: 31020ec93e2c
Revises: 3ad205277217
Create Date: 2021-07-13 18:14:42.127164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31020ec93e2c'
down_revision = '3ad205277217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('News', sa.Column('Source', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('News', 'Source')
    # ### end Alembic commands ###
