"""Add news table

Revision ID: 3ad205277217
Revises: 54d65dfc915d
Create Date: 2021-07-12 22:32:17.728059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ad205277217'
down_revision = '54d65dfc915d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('News',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('HashedUrl', sa.String(), nullable=False),
    sa.Column('DateTime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('HashedUrl')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('News')
    # ### end Alembic commands ###
