"""create user table

Revision ID: 54d65dfc915d
Revises: 
Create Date: 2021-06-19 17:40:40.866911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d65dfc915d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('DiscordId', sa.BigInteger(), nullable=False),
    sa.Column('Index', sa.String(length=8), nullable=False),
    sa.Column('Name', sa.String(length=32), nullable=False),
    sa.Column('Username', sa.String(length=32), nullable=False),
    sa.Column('Discriminator', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('DiscordId'),
    sa.UniqueConstraint('Index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    # ### end Alembic commands ###
