"""Cleanup

Revision ID: 593877bbf960
Revises: 888d2c668dc1
Create Date: 2021-03-09 20:54:39.266211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '593877bbf960'
down_revision = '888d2c668dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Posts')
    op.drop_table('PollOptions')
    op.drop_table('Polls')
    op.drop_column('Users', 'StatusFakultet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('StatusFakultet', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.create_table('Polls',
    sa.Column('PollId', sa.INTEGER(), server_default=sa.text('nextval(\'"Polls_PollId_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('MessageId', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ChannelId', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('UserId', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['Users.UserId'], name='Polls_UserId_fkey'),
    sa.PrimaryKeyConstraint('PollId', name='Polls_pkey'),
    sa.UniqueConstraint('Name', name='Polls_Name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('PollOptions',
    sa.Column('PollOptionId', sa.INTEGER(), server_default=sa.text('nextval(\'"PollOptions_PollOptionId_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('Icon', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('PollId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['PollId'], ['Polls.PollId'], name='PollOptions_PollId_fkey'),
    sa.PrimaryKeyConstraint('PollOptionId', name='PollOptions_pkey')
    )
    op.create_table('Posts',
    sa.Column('PostId', sa.BIGINT(), server_default=sa.text('nextval(\'"Posts_PostId_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('ChannelId', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('UserId', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['Users.UserId'], name='Posts_UserId_fkey'),
    sa.PrimaryKeyConstraint('PostId', name='Posts_pkey')
    )
    # ### end Alembic commands ###
