"""Remove role table

Revision ID: c8f455a14851
Revises: 593877bbf960
Create Date: 2021-03-21 21:09:43.359147

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c8f455a14851'
down_revision = '593877bbf960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UsersRoles')
    op.drop_table('Roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Roles',
    sa.Column('RoleId', sa.BIGINT(), server_default=sa.text('nextval(\'"Roles_RoleId_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('Name', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('ParentRole', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Value', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('RoleId', name='Roles_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('UsersRoles',
    sa.Column('UserId', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('RoleId', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['RoleId'], ['Roles.RoleId'], name='UsersRoles_RoleId_fkey'),
    sa.ForeignKeyConstraint(['UserId'], ['Users.UserId'], name='UsersRoles_UserId_fkey')
    )
    # ### end Alembic commands ###
