"""Remove channel model

Revision ID: eadb448b384a
Revises: c8f455a14851
Create Date: 2021-06-05 16:10:29.083733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eadb448b384a'
down_revision = 'c8f455a14851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Channels')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Channels',
    sa.Column('Id', sa.BIGINT(), server_default=sa.text('nextval(\'"Channels_Id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('Name', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Id', name='Channels_pkey')
    )
    # ### end Alembic commands ###
